package org.unibl.etf.ip.test;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.runners.MethodSorters;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@DisplayName("Student Add Tests")
public class StudentAddTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}

@DisplayName("Student Addition - Name Test")
@Test
public void studentAdd1() {
	driver.get("http://localhost:4200/");
	driver.manage().window().setSize(new Dimension(1058, 812));
	driver.findElement(By.linkText("Add Student")).click();
	driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
	driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[1]/input")).sendKeys("student1");
 driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).click();
 driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("student1@mail.com");
 driver.findElement(By.cssSelector(".ng-untouched")).click();
 {
   WebElement dropdown = driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[3]/select"));
   dropdown.findElement(By.xpath("//option[. = 'BCA']")).click();
 }
 driver.findElement(By.cssSelector(".btn-success")).click();
 driver.findElement(By.linkText("View Student")).click();
 vars.put("x", driver.findElement(By.cssSelector(".sorting_1")).getText());
 assertEquals(vars.get("x").toString(), "student1");
 vars.put("size", driver.findElements(By.xpath("//*[@id=\"DataTables_Table_1\"]/tbody/tr")).size());
 assertEquals(vars.get("size").toString(), "1");
}

@DisplayName("Student Addition - Email Test")
@Test
public void studentAdd2() {
  driver.get("http://localhost:4200/");
  driver.manage().window().setSize(new Dimension(1058, 812));
  driver.findElement(By.linkText("Add Student")).click();
  driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
  driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[1]/input")).sendKeys("student2");
  driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).click();
  driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("student2@mail.com");
  driver.findElement(By.cssSelector(".ng-untouched")).click();
  {
    WebElement dropdown = driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[3]/select"));
    dropdown.findElement(By.xpath("//option[. = 'BCA']")).click();
  }
  driver.findElement(By.cssSelector(".btn-success")).click();
  driver.findElement(By.linkText("View Student")).click();
  vars.put("size", driver.findElements(By.xpath("//*[@id=\"DataTables_Table_1\"]/tbody/tr")).size());
  assertEquals(vars.get("size").toString(), "2");
  vars.put("x", driver.findElement(By.cssSelector(".even > td:nth-child(2)")).getText());
  assertEquals("student2@mail.com", vars.get("x").toString());
}

@DisplayName("Student Addition - Branch Test")
@Test
public void studentAdd3() {
	driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1058, 812));
    driver.findElement(By.linkText("Add Student")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[1]/input")).sendKeys("student3");
    driver.findElement(By.cssSelector(".ng-invalid:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("student3@mail.com");
    driver.findElement(By.cssSelector(".ng-untouched")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("/html/body/app-root/div/app-add-student/div[1]/div[2]/div/form/div[3]/select"));
      dropdown.findElement(By.xpath("//option[. = 'MCA']")).click();
    }
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("View Student")).click();
    vars.put("size", driver.findElements(By.xpath("//*[@id=\"DataTables_Table_1\"]/tbody/tr")).size());
    assertEquals(vars.get("size").toString(), "3");
    vars.put("x", driver.findElement(By.cssSelector(".odd:nth-child(3) > td:nth-child(3)")).getText());
    assertEquals("MCA", vars.get("x").toString());
}

}


